server:
  port: 8086
#  servlet:
#    path: /demo
#配置日志
logging:
  config: classpath:logback-spring.xml
  #采用相对路径方式将日志文件输出到【log】
  file:
    name: log/demo.log

spring:
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#  #  mysql
#  datasource:
#      url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 45MB
      max-request-size: 50MB
      enabled: true

  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5

  mvc:
    static-path-pattern: /**